alg_name: "KN"
model_name: "/data2/hmpiao/FME/cached_model/Meta-Llama-3-8B-Instruct"
device: 4
model_parallel: true

lr_scale: 1.0
n_toks: 10
refine: false
batch_size: 1
steps: 1
adaptive_threshold: 0.2
p: 0.4